---
- name: Ensure Google signing key present
  ansible.builtin.apt_key:
    url: "{{ chrome_gpg_key_url }}"
    state: present
  become: true

- name: Ensure Google Chrome repo present
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] {{ chrome_repo_url }} stable main"
    filename: "google-chrome"
    state: present
    update_cache: yes
  changed_when: false
  become: true
