---
- name: Ensure Google Chrome repo present
  ansible.builtin.yum_repository:
    name: googlechrome
    description: Google Chrome repository
    state: present
    file: googlechrome
    baseurl: "{{ chrome_repo_url }}"
    gpgkey: "{{ chrome_gpg_key_url }}"
    gpgcheck: no
  become: true
